@CadmusApi_HostAddress = http://localhost:5050

GET {{CadmusApi_HostAddress}}/weatherforecast/
Accept: application/json

### POST login
POST {{CadmusApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "zeus",
  "password": "P4ss-W0rd!"
}
